ALTER TABLE business_locations 
ADD COLUMN IF NOT EXISTS location_id VARCHAR(100) AFTER name,
ADD COLUMN IF NOT EXISTS state VARCHAR(100) AFTER city,
ADD COLUMN IF NOT EXISTS country VARCHAR(100) AFTER state,
ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20) AFTER country;
